GET http://localhost:8080/matchmaking?email=me%40urjith.dev
Authorization:eyJhbGciOiJFUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHBpcnkiOjE3MzgxNzM1ODgsInV1aWQiOiJhMDJlNjI5Zi1hOTdkLTQ1ZDMtODdkNS03NTVhZjViMTQ5MGMifQ.tJ0bKyY5ty7imZozrIG0c4U-mGneOlfGMPEU1B9ypQKgXhWW_BZPQbkzForWn_VFDwoj1VvJFb13AZswTCFkQQ